package io.flutter.plugins

import androidx.annotation.Keep
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
class GeneratedPluginRegistrant {
    companion object {
        private const val TAG = "GeneratedPluginRegistrant"
        @JvmStatic
        fun registerWith(flutterEngine: FlutterEngine) {
            try {
                com.aidatpanel.app.PluginRegistrant.register(flutterEngine)
            } catch (e: Exception) {
                Log.e(
                    TAG,
                    "Error registering plugins. "
                    + "The app might crash if one of the plugins is used.",
                    e
                )
            }
        }
    }
}
